name = "Mise"
grammar = "toml"
path_suffixes = ["mise.toml", ".mise.toml", "mise.local.toml", ".mise.local.toml"]
line_comments = ["#"]

[indent]
unit = "  "
start_pattern = '^\s*\['
end_pattern = '^\s*'
